# Generated by Django 5.1 on 2025-11-22 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_owner_pledge_supporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraiser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pledge',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='image',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
