# Generated by Django 5.1 on 2025-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_alter_fundraiser_options_alter_pledge_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraiser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pledge',
            options={},
        ),
        migrations.RenameField(
            model_name='fundraiser',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fundraiser',
            name='target_amount',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='supporter',
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='goal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
