# Generated by Django 5.1 on 2026-01-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0006_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='product_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
